### Numpy

* Numpy is a python library
* It is used for Working with arrays
* it is short for Numerical Pyhton
* It is used for computation and processing of single and multi-dimensional array of elements.
* smaller memory consumption and better runtime behavior

In [79]:
import numpy as np

In [7]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [9]:
type(a)
# ndarray i.e n dimensional array 
# there are 1-d, 2-d, 3-d....so on.. n dimensional array

numpy.ndarray

In [11]:
a=np.array([1,2,3], dtype = float)
print(a)

[1. 2. 3.]


In [13]:
b= np.array([[1,2,3],[4,5,6]])
print(b)


[[1 2 3]
 [4 5 6]]


In [15]:
#get dimensions of a numpy array
a.ndim

1

In [17]:
b.ndim

2

In [19]:
d=np.array([[[[1,2,3],[4,5,6],[7,8,9]]]])
print(d)

[[[[1 2 3]
   [4 5 6]
   [7 8 9]]]]


In [21]:
d.ndim # it shows the dimension of that array

4

In [23]:
a

array([1., 2., 3.])

In [25]:
#get a shape of a numpy array
a.shape

(3,)

In [33]:
a.dtype

dtype('float64')

In [27]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [29]:
b.shape

(2, 3)

In [34]:
b.dtype

dtype('int32')

In [31]:
d

array([[[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]]])

In [32]:
d.shape

(1, 1, 3, 3)

In [35]:
d.dtype

dtype('int32')

### Accessing/changing specific elements, rows & columns etc.

In [37]:
a= np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [39]:
a.ndim

2

In [41]:
#get a specific elements [r,c]
a[0,3]

4

In [43]:
a[1,0]

8

In [45]:
a[1,5]

13

In [47]:
#get specific row from a numpy array
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [49]:
#get specific column from a numpy array
a[:,0]

array([1, 8])

In [51]:
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [53]:
a[0,3]=40 # change the 4th value in 1st row to 40
print(a)

[[ 1  2  3 40  5  6  7]
 [ 8  9 10 11 12 13 14]]


### Zeros/Ones/Full method in Numpy

In [57]:
np.zeros((3,3)) # here we are defining all the elements to zero

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [59]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [61]:
np.ones((3,3), dtype='int32')

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [64]:
np.full((3,3), 50, dtype = 'float64')

array([[50., 50., 50.],
       [50., 50., 50.],
       [50., 50., 50.]])

In [66]:
np.random.rand(4,4)

array([[0.04283357, 0.56759946, 0.8106331 , 0.60203226],
       [0.59991946, 0.77623271, 0.81355431, 0.42318503],
       [0.90286824, 0.38993527, 0.16966914, 0.27540542],
       [0.2549744 , 0.00939729, 0.04397491, 0.97156523]])

In [69]:
np.random.randint(-4,1, size=(3,3))

array([[-1, -2, -2],
       [-4,  0, -1],
       [-1, -4, -4]])

In [71]:
np.identity(5) # all left to right digonally value will be 1

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

### Practice Question

Q1. Extract all the first 3 rows of the last 5 columns in a given numpy 2D array 'a'?

In [75]:
a = np.array([[1,2,3,4,5,6],
             [10,20,30,40,50,60],
             [12,12,12,12,12,12],
             [11,21,31,41,51,61],
             [13,24,34,44,54,64]])
a

array([[ 1,  2,  3,  4,  5,  6],
       [10, 20, 30, 40, 50, 60],
       [12, 12, 12, 12, 12, 12],
       [11, 21, 31, 41, 51, 61],
       [13, 24, 34, 44, 54, 64]])

In [77]:
a[:3, -5:]

array([[ 2,  3,  4,  5,  6],
       [20, 30, 40, 50, 60],
       [12, 12, 12, 12, 12]])

Q2. Given a positive number 'n' greater than 2, create a Numpy array of size (nXn) with all zeros and ones such that the ones make a shape of "+"

In [83]:
# create an (nXn) array with all Zeros
n=5 
#if we don't want hard coded value ,if we wants user input then ,n=int(input())

z= np.zeros((n,n), dtype='int')
print(z)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [86]:
# make the middle row and column all 1's
z[n//2,:]=1
z[:,n//2]=1

#print the final value of z
print(z)

[[0 0 1 0 0]
 [0 0 1 0 0]
 [1 1 1 1 1]
 [0 0 1 0 0]
 [0 0 1 0 0]]


just to help you understand about n//2

In [91]:
a = np.array([[1,2,3,4,5,6],
             [10,20,30,40,50,60],
             [12,12,12,12,12,12],
             [11,21,31,41,51,61],
             [13,24,34,44,54,64]])
a

array([[ 1,  2,  3,  4,  5,  6],
       [10, 20, 30, 40, 50, 60],
       [12, 12, 12, 12, 12, 12],
       [11, 21, 31, 41, 51, 61],
       [13, 24, 34, 44, 54, 64]])

In [93]:
a[5//2,:] # it will give you the middle row

array([12, 12, 12, 12, 12, 12])

In [94]:
a[:,5//2] # it will give you the middle column

array([ 3, 30, 12, 31, 34])

In [95]:
a[5//2,:]=1
print(a)  # all the middle row will be 1

[[ 1  2  3  4  5  6]
 [10 20 30 40 50 60]
 [ 1  1  1  1  1  1]
 [11 21 31 41 51 61]
 [13 24 34 44 54 64]]


In [97]:
a[:,5//2]=1
print(a) # all the middle column value will be 1

[[ 1  2  1  4  5  6]
 [10 20  1 40 50 60]
 [ 1  1  1  1  1  1]
 [11 21  1 41 51 61]
 [13 24  1 44 54 64]]


### Airthmetic operation with Numpy- maths + Stats

In [112]:
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [109]:
a+2

array([3, 4, 5, 6])

In [115]:
#do it for " -,/,*,//,** " Almost all operations are satisfied
a**3

array([ 1,  8, 27, 64], dtype=int32)

In [117]:
a

array([1, 2, 3, 4])

In [119]:
a.min() # or we can write np.min(a)

1

In [121]:
a.max() # or we can write np.max(a)

4

In [124]:
a.mean() # or we can write np.mean(a)

2.5